var FHL = {} || FHL
FHL.CONSTANT = {} || FHL.CONSTANT
FHL.STR = {} || FHL.STR
FHL.DEBUG = {} || FHL.DEBUG
FHL.NET = {} || FHL.NET
FHL.LECTURE = {} || FHL.LECTURE
FHL.LECTURE.TEXT = {} || FHL.LECTURE.TEXT